sourcegraph/cody-vs

src/Cody.AgentTester/Program.cs, src/Cody.Core/Agent/IAgentService.cs, src/Cody.Core/Agent/InitializeCallback.cs, src/Cody.Core/Agent/ProgressNotificationHandlers.cs, src/Cody.Core/Agent/Protocol/ProgressOptions.cs, src/Cody.Core/Agent/Protocol/ProgressReportParams.cs, src/Cody.Core/Agent/Protocol/ProgressStartParams.cs, src/Cody.Core/Agent/Protocol/TestProgress.cs, src/Cody.Core/Cody.Core.csproj, src/Cody.Core/Infrastructure/IProgressService.cs, src/Cody.VisualStudio/Client/AgentClientOptions.cs, src/Cody.VisualStudio/Cody.VisualStudio.csproj, src/Cody.VisualStudio/CodyPackage.cs, src/Cody.VisualStudio/Services/ProgressService.cs
https://linear.app/sourcegraph/issue/CODY-3418/status-bar-for-codebase-index-progress
=> Progress bar for codebase index progress

CHANGELOG.md, CONTRIBUTING.md, README.md, docs/qa/Testing.md, src/Cody.VisualStudio/source.extension.vsixmanifest
- Update CHANGELOG.md to include changes for 0.0.1 release
- Update README.md with preview status information and installation instructions
- Update Testing.md with latest test plan
=> Release 0.0.1

src/Cody.Core/Infrastructure/WebViewsManager.cs, src/Cody.VisualStudio/CodyPackage.cs
CLOSE https://linear.app/sourcegraph/issue/CODY-3767/updatecurrentworkspacefolder-fails
1. Open VS with src\Cody.VisualStudio.Tests\TestProjects\ConsoleApp1 solution
2. No files are opened, Cody chat is not selected, Close VS.
3. Open VS again with the same solution (no errors should be visible in the "Cody" output)
=> Fixed NRE in UpdateCurrentWorkspaceFolder

src/Cody.UI/Controls/WebviewController.cs
CLOSE https://linear.app/sourcegraph/issue/CODY-3387/visual-studio-taskcanceledexception-while-closing-the-ide
=> TaskCanceledException while closing the IDE

CHANGELOG.md, src/Cody.VisualStudio/source.extension.vsixmanifest
- Update CHANGELOG.md to include changes for 0.0.2 release
- Update extension version to 0.0.2
=> Release 0.0.2

.github/workflows/cake-build.yml
CLOSE https://linear.app/sourcegraph/issue/CODY-3950/publish-tests-reports-during-ci
=> Added publishing tests results during CI

src/Cody.VisualStudio/CodyPackage.cs, src/Cody.VisualStudio/Services/SolutionService.cs
Improved logging for SolutionService.
=> Added logging when solution (workspace) is changed.

CONTRIBUTING.md
CLOSE https://linear.app/sourcegraph/issue/CODY-3931/document-the-decompiling-step
Added a new entry to Resources on using dotPeek to decompile the Visual Studio extension and view the source code
=> Doc: update contributing guide

.github/workflows/cake-build.yml, src/Cody.Core.Tests/Cody.Core.Tests.csproj, src/Cody.Core.Tests/CustomConfigurationTests.cs, src/Cody.Core.Tests/Properties/AssemblyInfo.cs, src/Cody.Core/Infrastructure/ConfigurationService.cs, src/Cody.sln
Introduced Cody.Core.Tests project with first unit tests for Custom Configuration serialization validation (#118)
=> Added tests for Custom Configuration JSON serialization.

.github/workflows/cake-build.yml, src/Cody.VisualStudio.Tests/ChatNotLoggedStateTests.cs, src/Cody.VisualStudio.Tests/PlaywrightTestsBase.cs
CLOSE https://linear.app/sourcegraph/issue/CODY-4234/e2e-test-sign-in-page-check-update
=> E2E Test: Sign in page check update

docs/dev/Release.md, docs/dev/versioning.md
=> Release documentation

agent/buildAgent.ps1, src/Cody.Core/Agent/NotificationHandlers.cs, src/Cody.Core/Ide/IVsVersionService.cs, src/Cody.Core/Infrastructure/ConfigurationService.cs, src/Cody.Core/Infrastructure/IVersionService.cs, src/Cody.Core/Infrastructure/VersionService.cs, src/Cody.UI/Cody.UI.csproj, src/Cody.VisualStudio/Cody.VisualStudio.csproj, src/Cody.VisualStudio/CodyPackage.cs, src/Cody.VisualStudio/Infrastructure/LoggerFactory.cs, src/Cody.VisualStudio/Services/VsVersionService.cs
CLOSE https://linear.app/sourcegraph/issue/CODY-4422/add-to-logs-information-about-version
- Cody version
- Agent version
- Visual Studio version (should be same as version in About window)
=> Add to logs information about versions

src/Cody.Core.Tests/StringExtensionsTests.cs, src/Cody.Core/Common/StringExtensions.cs, src/Cody.VisualStudio.Tests/ChatLoggedBasicTests.cs, src/Cody.VisualStudio.Tests/ChatNotLoggedStateTests.cs, src/Cody.VisualStudio/CodyPackage.cs, src/Cody.VisualStudio/Services/DocumentsSyncService.cs
https://sourcegraph.sentry.io/issues/6203833553/
https://sourcegraph.sentry.io/issues/6204352270/
1. Open solution
2. Open file in solution
3. Make some changes in file
4. Try to select part of edited code
=> Sentry error report fixes

src/Cody.VisualStudio/publishManifest.json
=> 'Overview' path fix

src/Cody.VisualStudio/Client/AgentClient.cs
=> Disable disconnection logging

src/Cody.VisualStudio/CodyPackage.cs, src/Cody.VisualStudio/Services/DocumentsSyncService.cs, src/Cody.VisualStudio/Services/StatusbarService.cs
- System.ObjectDisposedException on GetVisibleRange
- Running StatusBar service from UI thread
Start VS and start editing files, check the output window for errors.
=> Visible range fix

src/Cody.VisualStudio.Completions/Cody.VisualStudio.Completions.csproj
=> Use Version attribute for PackageReference

agent/agent.version, src/Cody.VisualStudio.Tests/ChatLoggedBasicTests.cs, src/Cody.VisualStudio.Tests/ChatNotLoggedStateTests.cs, src/Cody.VisualStudio.Tests/PlaywrightTestsBase.cs
Testing after agent version upgrate
=> Upgrate agent to version 1.66

src/Cody.VisualStudio/Services/DocumentsSyncService.cs
Catching exception and logging errors during `DocumentsSyncService.Initialize()`
N/A
=> Catching exception and logging errors during DocumentsSyncService.Initialize()

agent/agent.version
=> Upgrate agent to v1.78.2

README.md
=> Update images in README.md for Marketplace

README.md
n/a
@PiotrKarczmarz this one loads!
=> Add new autocomplete gif

docs/limitation.md, docs/qa/Testing.md
=> Autocomplete documentation update.

README.md
=> Add mp4 video

agent/agent.version
=> Cody agent updated to version 1.88.0

src/Cody.VisualStudio.Completions/Cody.VisualStudio.Completions.csproj, src/Cody.VisualStudio.Completions/Completions/CodyProposalManager.cs, src/Cody.VisualStudio.Completions/Completions/CodyProposalManagerProvider.cs, src/Cody.VisualStudio.Completions/LoggerFactory.cs
Support for logging autocomplete exceptions.
N/A
=> Added logging for autocomplete.

README.md
See:
https://sourcegraph.slack.com/archives/C073U3KE5DK/p1750877685127599
N/A
=> Updated usage plans

src/Cody.Core/Settings/UserSettingsService.cs, src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml
Hide autoedit before official release date.
N/A
=> Hide auto-edit

README.md
New video demonstrating how auto-edit works:
https://github.com/user-attachments/assets/8cb80ba9-76ab-4ec2-9f85-a41d44218f94
N/A
=> Video link update

src/Cody.VisualStudio.Completions/Completions/CodyProposalSource.cs
Additional Sentry logging to analyze autocomplete-related errors
N/A
=> Additional Sentry login

src/Cody.AgentTester/Cody.AgentTester.csproj, src/Cody.AgentTester/FakeInfobarNotifications.cs, src/Cody.AgentTester/Program.cs, src/Cody.Core/Agent/NotificationHandlers.cs, src/Cody.Core/Agent/Protocol/ShowWindowMessageParams.cs, src/Cody.Core/Cody.Core.csproj, src/Cody.Core/Ide/IInfobarNotifications.cs, src/Cody.Core/Ide/Notification.cs, src/Cody.Core/Infrastructure/ConfigurationService.cs, src/Cody.Core/Settings/UserSettingsService.cs, src/Cody.VisualStudio/Cody.VisualStudio.csproj, src/Cody.VisualStudio/CodyPackage.cs, src/Cody.VisualStudio/Services/InfobarNotifications.cs
This PR introduces notification support for Visual Studio and fixes configuration parsing issues:
- **Notification Infrastructure**: Added `IInfobarNotifications` interface and `InfobarNotifications` service to handle agent notifications via Visual Studio infobars
- **Agent Protocol**: Implemented `ShowWindowMessageParams` and updated `NotificationHandlers` to process notification requests from the agent
- **Auto-edit Default**: Changed auto-edit to be disabled by default, allowing agent to enable it automatically when user is eligible
1. Be sure `Enable Cody auto-edit` is turned OFF (`Tools -> Options -> Cody`)
2. **First scenario**: Open a solution
- Wait for the auto-edit notification
- Click `Switch to autocomplete`
- Check if `Enable Cody auto-edit` is still OFF
3. **Second …
=> Notifications infrastructure with custom auto-edit support

README.md
=> Added loop for video playback.

src/Cody.VisualStudio.Completions/Completions/CodyProposalSource.cs
Additional logging to analyze logged exceptions.
N/A
=> Additional logging for auto-edit

src/Cody.Core/Agent/TextDocumentNotificationHandlers.cs, src/Cody.VisualStudio/CodyPackage.cs
Error handling and logging for potential exceptions in:
-  ShowSaveDialog()
-  Edit() 
-  ShowTextDocument()
N/A
=> Error Handling & Logging for TextDocumentNotificationHandlers

agent/agent.version
Agent update to version 1.120.0
N/A
=> Agent update

.github/workflows/nightly.yml
Added authentication token for running oprypin/find-latest-tag and and building the agent. Updated UI tests access token to use S2 environment instead of DOTCOM.
N/A
=> Fixed nightly build

src/Cody.Core/Agent/Protocol/ProtocolAuthStatus.cs
This PR unifies the way subtypes are deserialized.
N/A
=> Replace custom converter with KnowSubTypes

src/Cody.Core/Agent/WebviewMessageHandler.cs
After implementing `textDocument/show`, there is no need to intercept link clicks in VS. These clicks are handled in the agent.
N/A
=> Remove link clicks interception
