CHANGELOG.md
src/Cody.Core/Infrastructure/IColorThemeService.cs
src/Cody.UI/Controls/WebView2Dev.xaml.cs
src/Cody.UI/Controls/WebviewController.cs
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Services/ThemeService.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-3622/webview-theme-should-update-on-theme-changed
https://github.com/user-attachments/assets/4b388c44-456d-4a91-8a79-a594e51a56f9
Test Plan:
Try following the steps shown in the demo video above to switch theme and confirm the webview is updated accordingly.

Update webview theme on editor theme change

---

CHANGELOG.md
src/Cody.AgentTester/Cody.AgentTester.csproj
src/Cody.AgentTester/FakeSecretStorageProvider.cs
src/Cody.AgentTester/Program.cs
src/Cody.Core/Agent/InitializeCallback.cs
src/Cody.Core/Agent/NotificationHandlers.cs
src/Cody.Core/Agent/Protocol/ClientCapabilities.cs
src/Cody.Core/Cody.Core.csproj
src/Cody.Core/Infrastructure/ISecretStorageService.cs
src/Cody.Core/Infrastructure/ISolutionService.cs
src/Cody.Core/Settings/IUserSettingsService.cs
src/Cody.Core/Settings/UserSettingsService.cs
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml.cs
src/Cody.UI/ViewModels/GeneralOptionsViewModel.cs
src/Cody.VisualStudio.Tests/ChatNotLoggedStateTests.cs
src/Cody.VisualStudio/Cody.VisualStudio.csproj
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Options/GeneralOptionsPage.cs
src/Cody.VisualStudio/Services/OptionsPage.cs
src/Cody.VisualStudio/Services/SecretStorageService.cs
src/build.cake

CLOSE https://github.com/sourcegraph/cody-vs/issues/72 https://linear.app/sourcegraph/issue/CODY-3619/implement-ivscredentialstorageservice-interface-for-storing-secrets https://linear.app/sourcegraph/issue/CODY-3618/agent-api-for-secret-storage-capability https://linear.app/sourcegraph/issue/CODY-3617/implement-agent-requests-for-secret-storage-capability
Try logout and then log back into Cody to confirm you can now use token redirect and secret storage via Agent:
This PR enables client capability for authentication (added in https://github.com/sourcegraph/cody/pull/5325) and secrets (added in https://github.com/sourcegraph/cody/pull/5348) that allows users to use the native webview for authentication in Cody for Visual Studio. 
The protocols for secret storage operations have also been …

Implement authentication and secret storage capability

---

src/Cody.UI/Controls/WebView2Dev.xaml.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-3677/visual-studio-webview-fails-to-initialize
This fixes an issue where having Cody installed in your local machine will result in Cody not working in Debug mode.
This issue is caused by the app directory name being separated in production and debug mode.

Dev: Fix cody dir name in Debug mode

---

src/Cody.Core/Agent/NotificationHandlers.cs
src/Cody.VisualStudio.Tests/TestsBase.cs
src/Cody.VisualStudio/CodyPackage.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-3723/visual-studio-editor-not-focused-after-auth-redirection

Fixed Visual Studio not focused after auth redirection

---

src/build.cake

CLOSE https://linear.app/sourcegraph/issue/CODY-2638/trim-unnecessary-language-files-from-the-agent-to-reduce-the-package

Trim unnecessary language files from the agent to reduce the package size

---

src/Cody.Core/Settings/IUserSettingsService.cs
src/Cody.Core/Settings/UserSettingsService.cs
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml.cs
src/Cody.UI/ViewModels/GeneralOptionsViewModel.cs
src/Cody.VisualStudio/Client/AgentClientOptions.cs
src/Cody.VisualStudio/Client/AgentProcessConnector.cs
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Options/GeneralOptionsPage.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-3900/add-accept-non-trusted-certificates-option-in-visual-studio

Accept non-trusted certificates option

---

src/build.cake

CLOSE https://linear.app/sourcegraph/issue/CODY-3749
- Update the `BuildCodyAgent` task to fetch all tags from the Cody repository and checkout the latest stable release tag (`vscode-v1.34.3`) instead of a specific commit
- Remove the hardcoded commit hash and replace it with the latest stable release tag
- This change ensures that the Cody agent is built using the latest stable release, providing the most up-to-date functionality and bug fixes

Build: Update Cody agent build to use latest stable release tag of Cody

---

src/Cody.UI/Views/MainView.xaml

CLOSE https://linear.app/sourcegraph/issue/CODY-3638/starting-debugger-would-cause-the-cody-webview-to-flash-the-loading
1. Run Visual Studio and open Cody window
2. Switch to "Solution Explorer"
3. "Loading Cody chat ..." shouldn't be visible during switching between tabs

Fixed visibility problem with "Loading Cody chat ..." when switching from and to the Tool Window

---

.github/workflows/cake-build.yml
src/build.cake

CLOSE https://linear.app/sourcegraph/issue/CODY-3944/cake-build-github-action-takes-at-least-40-mins-to-complete
Discussion with @BolajiOlajide in https://sourcegraph.slack.com/archives/C04MYFW01NV/p1727732199068899
Attempt to improve CI by:
- use caching
- split Build and Tests step
- increase instance resources

CI: use caching and split Build and Tests step

---

src/build.cake

`build.cake` fails if you have a Cody repo cloned, but have not fetched the stable release tag. This is because `GitFetch` does not fetch tags. Use `GitFetchTags` instead.
Delete the current Cody commit tag, and run `dotnet cake`.
```
cd ../cody-dist
git tags -d vscode-v1.34.3
cd ../src
dotnet cake
```

Fetch tags before trying to check them out

---

.github/workflows/nightly.yml
src/build.cake

CLOSE: https://linear.app/sourcegraph/issue/CODY-4069/run-build-off-cody-main-nightly-for-visual-studio
This change allows specifying the Cody branch or tag to use when building the Cody agent, instead of always using the latest stable release tag.
The `cody-branch` argument has been added to the `BuildCodyAgent` task, which defaults to the latest stable release tag (`vscode-v1.38.1`) if not provided.
This provides more flexibility in building the agent, allowing developers to test against specific Cody branches or tags as needed.

Dev: Allow specifying Cody branch or tag to build agent

---

src/Cody.Core/Agent/Protocol/ExtensionConfiguration.cs
src/Cody.Core/Cody.Core.csproj
src/Cody.Core/Infrastructure/ConfigurationService.cs
src/Cody.Core/Infrastructure/IConfigurationService.cs
src/Cody.Core/Settings/IUserSettingsService.cs
src/Cody.Core/Settings/UserSettingsService.cs
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml.cs
src/Cody.UI/ViewModels/GeneralOptionsViewModel.cs
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Options/GeneralOptionsPage.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-4103/allows-user-to-use-options-page-for-json-customconfiguration
Example custom configuration for Tools->Cody->Cody Settings:
```
{
'cody.autocomplete.enabled': false,
'cody.experimental.urlContext': true
}
```

Custom configuration support

---

src/Cody.VisualStudio/CodyPackage.cs

Improved dev workflow when switching to local Cody agent during debugging or by running VS Experimental without debugger attached. With this PR, Visual Studio doesn't need to be restarted every time when CODY_VS_DEV_PORT is added/changed (enabled/disabled).
Changing (enabling/disabling) "CODY_VS_DEV_PORT" always requires VS restart, because `GetEnvironmentVariable()` is using "Process" scope.
When using "Process" scope, VS loads all environment variables only once, at startup. Later, during run-time and also debugging, when VS child process is created, every call to `Environment.GetEnvironmentVariable("CODY_VS_DEV_PORT")` gets OLD state of variable copied from main VS process that started child VS process. For this reason, VS needs to be manually restarted every time when CODY_VS_DEV_PORT …

Updated CODY_VS_DEV_PORT variable scope to "User"

---

src/Cody.Core/Cody.Core.csproj
src/Cody.Core/DocumentSync/DocumentSyncCallback.cs
src/Cody.Core/Trace/FileTraceListener.cs
src/Cody.Core/Trace/LogioTraceListener.cs
src/Cody.Core/Trace/TraceEvent.cs
src/Cody.Core/Trace/TraceListener.cs
src/Cody.Core/Trace/TraceLogger.cs
src/Cody.Core/Trace/TraceManager.cs
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Services/DocumentsSyncService.cs

The change aims to add detailed tracing to the extension's code. Currently, we use logging to the VSs output window, but this has limitations and should be used for conveying basic information. Additionally, the output window is visible to users of the extension, so it should not contain too many entries and details. The place where details should be logged is tracing.
- Capability for dynamically enabling and disabling tracing
- When tracing is disabled, it does not impact performance
- Ability to filter entries additionally
- File logging (possibility to easy add custom targets where entries are logged)
- Ability to view state of the extension in real time using external tools

Adding tracing

---

.github/workflows/release-preview.yml
CHANGELOG.md
README.md
docs/dev/Release.md
docs/limitation.md
docs/qa/Testing.md
src/Cody.VisualStudio/source.extension.vsixmanifest
src/build.cake

The extension is now in experimental mode. 
This PR includes the following changes:
- Update extension version to 0.1.0
- Update README.md to reflect the extension is now experimental
- Update documentation to reflect the extension is experimental
- Update release workflow to use the correct name
- Update the Cody stable release tag to the next stable version `vscode-v1.40.0`
Do not 
To upload the vsix package to the Marketplace:
1. Sign in with an admin account ( ask the visual studio team or security team to add you to the sourcegraph org)
2. Go to the [cody-vs manage page](https://marketplace.visualstudio.com/manage/publishers/sourcegraph/extensions/cody-vs/edit) and click on the pencil icon to upload the vsix package you downloaded from the GitHub Release page:
3. Update the Overview …

Release 0.4.0

---

CHANGELOG.md
src/Cody.VisualStudio/source.extension.vsixmanifest

I overlooked the previous [PR](https://github.com/sourcegraph/cody-vs/pull/128), the version number should be v0.1.0
once this gets merged I can re-tag

Release v0.1.0

---

.github/workflows/cake-build.yml
.github/workflows/nightly.yml
src/Cody.Core.Tests/CustomConfigurationTests.cs
src/Cody.VisualStudio.Tests/ChatLoggedBasicTests.cs
src/Cody.VisualStudio.Tests/ChatNotLoggedStateTests.cs
src/Cody.VisualStudio.Tests/Cody.VisualStudio.Tests.csproj
src/Cody.VisualStudio.Tests/PlaywrightTestsBase.cs
src/Cody.VisualStudio.Tests/Properties/AssemblyInfo.cs
src/Cody.VisualStudio.Tests/ScreenshotUtil.cs
src/Cody.VisualStudio.Tests/TestsBase.cs
src/Cody.sln

Implemented ability to automatically take screenshots for UI tests, locally and when using GitHub Actions. A screenshot is taken at the end of every UI test (all tests inherited from `PlaywrightTestsBase` class).
Currently  `VsTestSettings(TakeScreenshotOnFailure = true)` attribute doesn't work for async tests (`Task async` or `void async`), which is way the custom solution was implemented.
- Updated Cake Build and Nightly Build to include support for taking screenshots via GitHub Actions.
- Additional logging for Solution_Name_Is_Added_To_Chat_Input(), which very rarely fails.
- Additional logging for PlaywrightTestsBase.GetChatContextTags()
- Fixed logging for TestBase.OpenSolution()

Support for automatically taking screenshots at the end of each UI test (passed or failed).

---

CHANGELOG.md
src/Cody.VisualStudio/source.extension.vsixmanifest
src/build.cake

- Update the extension version to 0.1.1 in the `source.extension.vsixmanifest` file
- Update the cody stable release tag to `vscode-v1.38.3` in the `build.cake` file
- Add a changelog entry for the 0.1.1 release, noting the fix for the login issue

Release 0.1.1

---

agent/agent.version
src/Cody.sln

CLOSE https://linear.app/sourcegraph/issue/CODY-4360/bump-vs-to-use-cody-v146x

Cody agent updated to version vscode-v1.44.0 (tag)

---

.github/workflows/build.yml
src/Cody.VisualStudio.Tests/ChatLoggedBasicTests.cs
src/Cody.VisualStudio.Tests/PlaywrightTestsBase.cs
src/Cody.VisualStudio/Services/ThemeService.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-4322/make-entered-prompt-show-up-in-today-history-working-in-the-ci
- Entered_Prompt_Show_Up_In_Today_History() is finally working
- New test  Active_File_Match_Current_Chat_Context()
- Added NewChat() method
- Added delay to ShowChatTab() method
- DismissStartWindow() method called at the of EnterChatTextAndSend() because VS modal dialog for selecting project is showing up in the foreground for some reason

UI tests improvements

---

src/Cody.Core/Logging/Logger.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-4470/sentry-is-logging-inner-exception-instead-of-the-original-exception

Fixed not using original exception when logging error to Sentry

---

.github/workflows/build.yml
src/Cody.VisualStudio.Tests/ChatLoggedBasicTests.cs
src/Cody.VisualStudio.Tests/Cody.VisualStudio.Tests.csproj
src/Cody.VisualStudio.Tests/PlaywrightTestsBase.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-4471/improved-handling-for-vs-start-window-during-ui-tests
Refactored ChatLoggedBasicTests:
- moved calls WaitForPlaywrightAsync() to constructor
- added taking screenshots at the beginning of a test

Improved handling for VS Start Window during UI tests

---

.github/workflows/build.yml
.github/workflows/publish.yml

CLOSE https://linear.app/sourcegraph/issue/CODY-4472/cody-agent-is-cached-using-only-agentagentversion-file
Changes in the agent/buildAgent.ps1 and agent/runBuildAgent.ps1 don't trigger building agent, but they should.
Example - latest changes to buildAgent.ps1, like copying `agent.version` file to VSIX installer, didn't take effect because old cache from the agent was used. In this case call to `VersionService.GetAgentVersion()` fails.

Fixed agent cache issue when only single agent.version file was used to create agent cache

---

agent/buildAgent.ps1
src/Cody.VisualStudio/Cody.VisualStudio.csproj
src/Cody.VisualStudio/source.extension.vsixmanifest

Index.js.map makes debugging the agent easier so it should be added to the debug build

Include index.js.map file in debug build

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-auditor.yml
.github/workflows/semgrep.yml

This PR adds two GH actions in order to comply with [Sourcegraph Repository Controls](https://www.notion.so/sourcegraph/Repository-policies-and-controls-0e9d5ae3ef4949b3bf0de48b247dc7d3):
- pr-auditor ensures that the PR has a Test Plan
- semgrep is our SAST tool
closes https://linear.app/sourcegraph/issue/SEC-2167/review-vs-repo-controls

Add repository controls

---

agent/agent.version
src/Cody.VisualStudio.Tests/ChatNotLoggedStateTests.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-4438/update-unit-test-for-unified-auth-page
N/A

Updated UI tests for unified auth page with agent bump to vscode-v1.54.x

---

src/Cody.Core/Cody.Core.csproj
src/Cody.Core/Logging/SentryExceptionFilter.cs
src/Cody.Core/Logging/SentryLog.cs
src/Cody.VisualStudio/CodyPackage.cs

- Sentry logs all errors from Visual Studio, not caring whether the errors originate in Cody or outside it. This PR limits the recording of the most common errors from outside the extension
- Enriching error information about the user
Watch for errors in Sentry to see if any new ones appear in:
https://sourcegraph.sentry.io/issues/6123815161
https://sourcegraph.sentry.io/issues/6152558932
https://sourcegraph.sentry.io/issues/6115819359

Sentry enriching events and exception filtering

---

.github/workflows/semgrep.yml

CI has been failing for closed pull request events, fixing that by removing the `closed` events as this already runs on pre-merge events
- CI 🟢

chore(security): Fix closed events for semgrep

---

src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml.cs
src/Cody.UI/ViewModels/GeneralOptionsViewModel.cs
src/Cody.VisualStudio/Options/GeneralOptionsPage.cs

This PR removes the 'Sourcegraph URL' option from the settings window because it has become part of the new login screen.
Check if the option is unavailable in the settings window.

Remove Sourcegraph URL option

---

src/Cody.Core/Logging/SentryLog.cs
src/Cody.VisualStudio/CodyPackage.cs

Added tag "vs" which includes Visual Studio version when reporting errors:
- during initialization VS version is reported independently by sending `Initialized` message
Turn on logging for dev environment in the `SentryLog` class, and check if `Initialized` is properly logged in the Sentry Dashboard.

Reporting Visual Studio version to Sentry

---

src/Cody.Core.Tests/Cody.Core.Tests.csproj
src/Cody.Core.Tests/StringExtensionsTests.cs
src/Cody.Core/DocumentSync/DocumentSyncCallback.cs
src/Cody.VisualStudio/Completions/CodyProposalSource.cs
src/Cody.VisualStudio/Completions/CodyProposalSourceProvider.cs
src/Cody.VisualStudio/Services/DocumentsSyncService.cs

- Create a new solution
- Start adding code
- Check if 'grey code' with suggestions appears
- Accept the suggestions by pressing `Tab`
- Reject the suggestion by pressing `Esc`

Document sync & completions fix

---

src/Cody.Core/DocumentSync/DocumentSyncCallback.cs
src/Cody.VisualStudio.Tests/ChatLoggedBasicTests.cs
src/Cody.VisualStudio.Tests/ChatNotLoggedStateTests.cs
src/Cody.VisualStudio/Services/DocumentsSyncService.cs

Check for errors in logs after loading WPF solution

Fix for missing selection data

---

src/Cody.AgentTester/Program.cs
src/Cody.Core/Agent/Protocol/ClientCapabilities.cs
src/Cody.Core/Infrastructure/ConfigurationService.cs

Enabling terminal capability in Visual Studio for testing agentic chat: https://sourcegraph.com/github.com/sourcegraph/cody@main/-/blob/agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientCapabilities.kt?L22
- Create a new solution
- Start adding code
- Check if shell commands can be executed
- Verify that the shell capability is properly configured in the client

feat(agent): add shell capability support

---

src/Cody.AgentTester/Program.cs
src/Cody.Core/Agent/Protocol/ExtensionConfiguration.cs
src/Cody.Core/Agent/WebviewMessageHandler.cs
src/Cody.Core/Infrastructure/ConfigurationService.cs
src/Cody.Core/Infrastructure/ISecretStorageService.cs
src/Cody.Core/Settings/IUserSettingsService.cs
src/Cody.Core/Settings/UserSettingsService.cs
src/Cody.VisualStudio.Tests/PlaywrightTestsBase.cs
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Services/SecretStorageService.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-4620/cody-does-not-stay-signed-in-after-closing-visual-studio
1. Server endpoint and access token is no longer set via `ExtensionConfiguration`, because in a specific scenario, it could cause invalidating an access token when VS is restarted (probably agent related bug when migrated to the new secret storage driven sign in workflow).
2. Fixed NRE in the `SecretStorageService` when `Set()` method is called with empty/null key (not allowed by `IVsCredentialStorageService` implementation).
3. Moved event `AuthorizationDetailsChanged` from `UserSettingsService` to `SecretStorageService`
- introduced  `IsEndpoint()` as a heuristic logic to detect if the agent changed account and/or access token.
4. Removed code handling `signout/signin` commands …

Updated authorization to the latest agent workflow.

---

src/Cody.VisualStudio/Cody.VisualStudio.csproj

Autocomplete compatibility fix allowing to support autocomplete starting from Visual Studio VS 17.6+
It was tested against VS versions:
- 17.7.6
- 17.9 Preview 2
- 17.10.3
- 17.12
- 17.13.0 Preview 2.1
Internally `Microsoft.VisualStudio.Language` version is set to 17.0.0.0 after compilation, regardless of `Microsoft.VisualStudio.Language` version used as nuget package. The important part is `Microsoft.VisualStudio.Threading` library, which version set explicitly to match nuget `Microsoft.VisualStudio.Language` version.
1. Test autocomplete using your current VS version, and others if they are available.

Switched to Microsoft.VisualStudio.Language v17.6.268 - Autocomplete compatibility fix part 1

---

src/Cody.Core/Common/StringExtensions.cs
src/Cody.VisualStudio/Services/DocumentsSyncService.cs

- The previous version required the creation of all TextViews at the moment of opening the solution, which affected the loading performance of the solution. The new version uses lazy loading.
- Eliminating the active document object with references to the currently displayed document. This should eliminate problems with nulls when the object's state was being read and modified from different threads.
- Managing handlers to eliminate the possibility of losing certain events
Check for nulls in OnTextBufferChanged in the logs

Document synch refactor

---

src/Cody.Core/Logging/ISentryLog.cs
src/Cody.Core/Logging/Logger.cs
src/Cody.Core/Logging/SentryLog.cs

Support for message and caller method name parameters, internally exposed in the `Logger` class.
Create a test exception, and check if it's logged in the Sentry (`dev` environment).

Extended logging for SentryLog

---

src/Cody.Core/Infrastructure/ConfigurationService.cs

Added JSON context to configuration serialization error
Create a invalid JSON configuration, and check if it's logged in the Sentry (dev environment).

Added JSON context to configuration serialization error

---

src/Cody.VisualStudio/Services/DocumentsSyncService.cs

Handling the situation when Initialized() is called from a non-UI thread.
Cannot be manually tested.

Run Initialize() from UI thread

---

src/Cody.Core/Logging/Logger.cs
src/Cody.Core/Logging/SentryLog.cs
src/Cody.VisualStudio/Client/AgentClient.cs
src/Cody.VisualStudio/CodyPackage.cs

Check message availability in Sentry panel

Enable message logging in Sentry

---

src/Cody.Core/Infrastructure/ConfigurationService.cs
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml
src/Cody.UI/ViewModels/GeneralOptionsViewModel.cs
src/Cody.VisualStudio/Options/GeneralOptionsPage.cs

- Adding validation to custom configuration in the options window
- Attempting to automatically repair an already existing json configuration
1. Open the options window
2. Select Cody settings
3. Try entering an invalid json in the custom settings field

Custom settings validation

---

src/Cody.VisualStudio/Services/DocumentsSyncService.cs

When opening a solution via a .sln file, chat incorrectly displays the name of the currently active document.
- start Visual Studio by clicking on the file with the solution (.sln). 
- once solution is open, active document must match the name tag in the chat window

Send DidFocus during initialization. 

---

src/Cody.Core/Cody.Core.csproj
src/Cody.Core/Logging/SentryLog.cs

Disable error logging to Sentry after 180 days from build date. The change is intended to limit the number of events sent. We are mainly interested in the latest versions of the extension so older versions should be out of the scope after six months.
Check if after 6 months the extension version logs any errors to Sentry 😉

Sentry time bomb

---

src/Cody.VisualStudio/Services/DocumentsSyncService.cs

This PR adds support for non-text documents by skipping them during agent synchronization. Examples of such documents could be images. 
Open solution and add the image file. Then try to open the image as a document.

Skip non-text documents

---

src/Cody.VisualStudio/Services/DocumentsSyncService.cs

Added debug asserts in the Initialize() method will help to monitor breaking of internal contract - `openNotificationSend` and `isSubscribed` should be always empty when Initialize() is called.
In debug mode those asserts should be never called after opening a new solution.

Added debug asserts in the Initialize() method.

---

CONTRIBUTING.md
docs/dev/Release.md

Updated release doc, and link fix 

---

src/Cody.UI/Cody.UI.csproj
src/Cody.UI/Controls/CodyWebView2.cs
src/Cody.UI/Controls/WebView2Dev.xaml

CLOSE https://linear.app/sourcegraph/issue/CODY-4814/visual-studio-home-and-end-key-behavior
CLOSE https://linear.app/sourcegraph/issue/CODY-5463/fix-issue-with-end-key-functionality
This PR disables the custom key handling in WebView2 - `Home` and `End` weren't working properly when an user tried to navigate through text in the prompt.
1. Open Cody Tool Window
2. Write a prompt and navigate in the text by pressing Home and End keys

Fixes handling Home/Enter keys by the Cody Chat when editing prompt

---

src/Cody.VisualStudio/Client/AgentClient.cs

Added `Debug.Assert()` to ease monitoring when the agent disconnects. It will make easier to check if the agent successfully restarts, and will help investigating the root cause of disconnecting.
[Relevant logs](https://sourcegraph.sentry.io/issues/6123388490/?project=4508375896752129&query=is%3Aunresolved%20release.version%3A0.3.1.0&referrer=issue-stream&statsPeriod=2d&stream_index=0
)
N/A

Added Debug.Assert to monitor when the agent disconnects.

---

src/Cody.Core/Agent/INotificationHandler.cs
src/Cody.Core/Agent/NotificationHandlers.cs
src/Cody.Core/Agent/Protocol/ProtocolAuthStatus.cs
src/Cody.Core/Cody.Core.csproj
src/Cody.Core/Infrastructure/ISecretStorageService.cs
src/Cody.Core/Infrastructure/WebViewsManager.cs
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Services/SecretStorageService.cs

Updated the authorization flow to use the "authStatus/didUpdate" notification from the agent:
- Removed the heuristic for detecting log in/log out from SecretStorageService.
- Added support for the "authStatus/didUpdate" flow in NotificationHandlers.
- Added serialization support for the agent's ProtocolAuthStatus discriminated union type using ProtocolAuthStatusConverter.
Added support to wait for the chat to be fully loaded during debugging when a debugger is attached (no more timeouts).
1. Cody log out state
- Log in to Cody, look for `Pending validation: true/false` and `Authenticated: true` in the `Cody Notifications` output
- Successful login
2. Cody log in state
- Log out from Cody, look for `Pending validation: false` and `Authenticated: false`  output
- Successful logout

Updated the authorization flow to use the "authStatus/didUpdate"

---

src/Cody.UI/Cody.UI.csproj
src/Cody.UI/Controls/CodyWebView2.cs
src/Cody.UI/Controls/WebviewController.cs

The chat uses WebView2, which has always painted itself as the top window enclosing everything underneath. This was a known issue that, after years, was finally resolved by Microsoft (https://github.com/MicrosoftEdge/WebView2Feedback/issues/286). This PR changes WebView2 controls to the latest version that respects z-order in WPF.
Try opening another window above the chat window or docking it to the side of the ide and expanding it over the chat. In either case, the window above the chat should not be overlapped by the chat.

Prevent webview to overlap other controls

---

agent/agent.version
src/Cody.Core/Agent/Protocol/ClientCapabilities.cs
src/Cody.Core/Infrastructure/ConfigurationService.cs

Turn on CopyOnlyAction capability to hide SmartApply button with is not supported.
N/A

Update agent and turn on CopyOnlyAction capability

---

src/Cody.UI/Controls/WebviewController.cs

CLOSE https://linear.app/sourcegraph/issue/QA-723/visual-studio-user-is-navigated-to-in-app-browser-instead-of-browser
User is navigated to In-App Browser instead of Browser after clicking Explore Prompt Library
Try to open Explore Prompt Library from Prompts menu. The page should open in the system browser.

Open Explore Prompt Library in system browser

---

src/Cody.VisualStudio.Completions/Completions/CodyProposalManager.cs
src/Cody.VisualStudio.Completions/Completions/CodyProposalManagerProvider.cs
src/Cody.VisualStudio.Completions/Completions/CodyProposalSource.cs
src/Cody.VisualStudio.Completions/Completions/CodyProposalSourceProvider.cs
src/Cody.VisualStudio.Completions/LoggerFactory.cs

Ported from #293 with updated logging architecture for Cody.VisualStudio.Completions
Original description:
Extra logging visible in the Output window. This could be useful in case user complains about the lack of autocomplete/autoedit. The logging writes each step of the suggestion creation process. To see logs in Output window, force autocomplete using the `Alt + .` shortcut.
Trigger auto-edits via `Alt + .` and observe "Cody Completions" output window.

Added logging for autocomplete v2

---

src/Cody.Core.Tests/Cody.Core.Tests.csproj
src/Cody.Core.Tests/ConfiguartionFileJsonTests.cs
src/Cody.Core/Common/Configuration.Setup.cs
src/Cody.Core/Common/Configuration.cs
src/Cody.VisualStudio/Cody.VisualStudio.csproj
src/Cody.VisualStudio/CodyPackage.cs

Resolves JSON deserialization issues where port values were being parsed as `int` instead of `long` types. Added error handling, logging, and comprehensive test coverage for configuration file parsing scenarios.
`CodyDevConfig.json` is now included in VSIX installer in Debug mode and used during run-time.
1. Uncomment RemoteAgentPort and TraceLogioPort in `CodyDevConfig.json` and observe output window for any errors when accesing those properties from `Configuration` class.

Fix CodyDevConfig.json parsing for RemoteAgentPort/TraceLogioPort

---

src/Cody.Core/Settings/UserSettingsService.cs
src/Cody.UI/Controls/Options/GeneralOptionsControl.xaml

Reverts sourcegraph/cody-vs#301 and unhide autoedit
N/A

Revert "Hide auto-edit"

---

src/Cody.Core/Logging/SentryLog.cs
src/Cody.UI/Controls/WebView2Dev.xaml.cs
src/Cody.UI/Controls/WebviewController.cs
src/Cody.VisualStudio.Completions/LoggerFactory.cs
src/Cody.VisualStudio/Client/AgentClient.cs
src/Cody.VisualStudio/CodyPackage.ErrorHandling.cs

Add support for Visual Studio shutdown state in the extension. So far, Cody has not used the information that the IDE is about to shut down and tried to continue working. This led to many resource dispose exceptions during app exit. This PR adds support for shutdown state and reduces number of errors logged to Sentry.
N/A

Use of the shutdown state in Cody logic

---

src/Cody.VisualStudio/Services/VsVersionService.cs

Visual Studio preview versions contain a postfix in the version number (e.g. “17.14.2 preview 2”), which prevents the version from being parsed correctly. This PR checks if postfix exists and cuts it out before parsing.
N/A

Parses version string even when it contains postfix

---

src/Cody.VisualStudio/Services/ThemeService.cs

CLOSE https://linear.app/sourcegraph/issue/CODY-6146/visual-studio-theme-accessibility-issue
These changes [together with 8152](https://github.com/sourcegraph/cody/pull/8152) improve menu coloring in the chat window and in the @ menu. The change is mainly visible in blue/blue (extra contrast) themes.
Before
After
Change the theme color to Blue (extra contrast) and compare with the screenshot above.

Improve Visual Studio themes

---

src/Cody.VisualStudio/Client/AgentClient.cs

Adding a check to see if the connector to the agent is not null during the VS shutdown process
N/A

Check if connector is not null during shutdown 

---

src/Cody.VisualStudio.Completions/Completions/CodyProposalSource.cs

Fixing the way autocomplete suggestions are created. Event handling `ContentTypeChanged` to avoid errors with text buffer.
N/A

Autocomplete exception fixes

---

src/Cody.VisualStudio/Client/AgentClient.cs
src/Cody.VisualStudio/Client/RemoteAgentConnector.cs

1. Added Connection Retry Logic with Timeout 
- Implemented 5-minute timeout for connection attempts
- Added retry mechanism with 5-second intervals between attempts
- Enhanced error handling for TCP connection failures
2. Improved Logging and Debugging 
- Added detailed disconnect logging with debug and info messages
- Enhanced connection status tracking
1. Uncomment `RemoteAgentPort` section in `CodyDevConfig.json` file
2. Run Cody in Debug mode
3. Check if Cody is trying to connect via TCP port
```
[ProcessId:15532] [ThreadId:15] Debug [RemoteAgentConnector.Connect] Try to connect to port:3113 ...
```

The agent debugging improvements via TCP connection

---

src/Cody.Core/Common/StringExtensions.cs
src/Cody.VisualStudio/CodyPackage.ErrorHandling.cs
src/Cody.VisualStudio/CodyPackage.cs

Exceptions not related to Cody go to Sentry. This is caused by reporting all unhandled exceptions from VS. This change causes logging of exceptions that have something to do with Cody.
N/A

Filtering out exceptions not related to Cody

---

agent/agent.version

Update Cody agent to v1.114.0, which removes PLG login options.
1. PLG login options aren't showing up.

Updated agent version to remove PLG login options.

---

src/Cody.UI/Cody.UI.csproj
src/Cody.UI/Controls/CodyWebView2.cs

After updating `Microsoft.Web.WebView2` to version `1.0.3296.44` some users have started reporting problems with the chat rendering (an empty Cody window).
Looks like last update to `1.0.3351.48` doesn't resolve the issue also, so downgrading to `1.0.2592.51` which is the last good working version. Unfortunately it does not have fix for https://github.com/MicrosoftEdge/WebView2Feedback/issues/286 (WebView2 is always on the top of the other controls).
Users are reporting a blank Cody window, but looks like internally that the page is loaded, and when interacting with the control the cursor is changing and reacting to different page areas (e. g. buttons).
More context: https://sourcegraph.slack.com/archives/C073U3KE5DK/p1753121170575139
Probably related:
1. …

WebView2 library downgrade

---

src/Cody.Core/Agent/IAgentService.cs
src/Cody.Core/Agent/Protocol/ExecuteCommandParams.cs
src/Cody.Core/Agent/TextDocumentNotificationHandlers.cs
src/Cody.Core/Cody.Core.csproj
src/Cody.Core/Infrastructure/IStatusbarService.cs
src/Cody.VisualStudio/Cody.VisualStudio.csproj
src/Cody.VisualStudio/CodyPackage.Commands.cs
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/CodyPackage.vsct
src/Cody.VisualStudio/CommandIDs.cs
src/Cody.VisualStudio/Services/StatusbarService.cs

This PR adds standard commands that automate and speed up workflow in Cody. You get the following core (built-in) prompts:
- document-code
- explain-code
- find-code-smells
- generate-unit-tests
Commands are available when user is logged in. They are available in the editor's context menu. Commands can also be invoked using keyboard shortcuts, which can be configured in Visual Studio settings.
**Scenario I**
1. Select a block of code in the editor (e.g. one function)
2. Click right mouse button and choose Cody > Generate unit tests
3. Make sure new chat with generated unit tests code appears
**Scenario II**
1. Select a block of code in the editor (e.g. one function)
2. Click right mouse button and choose Cody > Explain code
3. Make sure new chat with generated unit tests code appears …

Build-in prompts commands

---

src/Cody.Core/Agent/NotificationHandlers.cs
src/Cody.Core/Cody.Core.csproj
src/Cody.Core/Infrastructure/IToastNotificationService.cs
src/Cody.UI/Cody.UI.csproj
src/Cody.UI/ViewModels/ToastViewModel.cs
src/Cody.UI/Views/ToastView.xaml
src/Cody.UI/Views/ToastView.xaml.cs
src/Cody.VisualStudio/Cody.VisualStudio.csproj
src/Cody.VisualStudio/CodyPackage.cs
src/Cody.VisualStudio/Services/ToastNotificationService.cs

This PR adds support for notifications from the agent. They can appear as text in the status bar or as a window popping up in the lower right corner of the main window. The window version appears when the notification contains actions. In this case, they appear as buttons in the window.
1. Log out of Cody
2. Log in again
3. A notification should appear in the status bar: "Signed in to `url`"

Support for notifications

---

src/Cody.Core/Agent/EditTaskNotificationHandlers.cs
src/Cody.Core/Infrastructure/IDocumentService.cs
src/Cody.VisualStudio/Services/DocumentService.cs

Implementation of `textEditor/selection` and `textEditor/revealRange` endpoints. With their help agent will be able to select and scroll through code. Such actions are used by the agent, for example, during edits to show the user what has been changed at the end of larger file.
N/A

textEditor/selection and textEditor/revealRange endpoints

---

src/Cody.VisualStudio.Tests/PlaywrightTestsBase.cs

Changed text for detecting login screen. The old text is probably not visible to Playwright, because Cody notification covers it. Although is should be rendered fine, but maybe this is the issue caused by WebView2 rendered on top of other controls (current version which is used), but in this case it is covered by "Cody notification" window.
1. Green `Cody_Enterprise_Section_Is_Present()` test.

[UI Tests] Changed text for detecting login screen
